### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by libook** [d-band/koa-mapper#14]
Hi, I am using koa for developing web services. And I am looking for tools for handling validations and documentations for HTTP APIs.
I am trying to use JSON schema for the validation of HTTP requests. Seems that the validation needs has been met.
In other hand, open API seems to be a good tool for documentation. Then I found this project.

Is this project still maintained?
Is there any milestones for improvements and new features?

**Comment by helloyou2012** [comment]
@libook yes, we will add `ts` support, and the api maybe change. If you have any suggestion welcome. If you are interested in this project, welcome to join in.

**Comment by libook** [comment]
@helloyou2012 Nice to see your replying.
I wonder that if this is a project for open purpose or just for private business needs.
Would you like to describe the vision of this project?

**Comment by helloyou2012** [comment]
This is a permanent open source project with MIT license, and we use it in production from the start. For details see: https://zhuanlan.zhihu.com/p/58465391

**Comment by libook** [comment]
@helloyou2012 OK, I'll try this.
And I can help if there is need.
