### ISSUE TITLE
请问在 throwBodyError 中能拿到 ctx 对象吗

### ISSUE THREAD

**Issue by bluescurry** [d-band/koa-mapper#21]
我的诉求是在 throwBodyError 方法中可以直接返回 ctx.response.body = 'xxx字段信息错误';前端可以拿到这个desc，而不是 throw new Error

**Comment by helloyou2012** [comment]
@H5futurehreohanshuo 这样不太好，因为如果这里不抛出错误那后面的函数依旧会执行。因此最好的方式是这里抛出 Error，错误处理统一做，如：

```js
async function errorHandler(ctx, next) {
  try {
    await next();
  } catch (err) {
    // 这里统一处理错误
    ctx.type = 'application/json';
    ctx.body = { message: err.message };
  }
}
app.use(errorHandler);
```

**Comment by bluescurry** [comment]
> @H5futurehreohanshuo 这样不太好，因为如果这里不抛出错误那后面的函数依旧会执行。因此最好的方式是这里抛出 Error，错误处理统一做，如：
> 
> ```js
> async function errorHandler(ctx, next) {
>   try {
>     await next();
>   } catch (err) {
>     // 这里统一处理错误
>     ctx.type = 'application/json';
>     ctx.body = { message: err.message };
>   }
> }
> app.use(errorHandler);
> ```

懂了，throw Error，然后做统一的错误处理。多谢^_^
